### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-js-serving-content-with-express-OctGcX#1]
@egillespie Can you take a look at this? It's [hosted here](https://goshuama-kfxl35erbteu5octgcx.herokuapp.com/) and meets the following criteria:

- [x] No code is repeated in your files; create a partial for any shared elements (`nav`, `head`, `header`, etc.)
- [x] Make a navigation to move throughout your site, using `forEach` to create a set of links to other data pages
- [x] Each item should have an object with an image, a link, a title, and more properties based on your topic (i.e. sandwich ingredients, movie release date, etc.)
- [x] Include at least 3 data pages and a homepage; routes should be created in Express for each
- [x] Use data appropriately with HTML tags (paragraphs in `p` tags, headings in `h1`-`h6`, etc.)
- [x] Use `express.static` to create a folder for static assets (images, stylesheets, etc.)
- [x] Include a `.gitignore` file so that `node_modules` and any other unnecessary files are not commited to github

**Comment by egillespie** [comment]
Hi @amanuel1995, I love how you've made a lot of reusable partials in your project! Overall your site looks great. I do have some suggestions to help you better satisfy criteria 3, though:

### Remove `nav.ejs`

This file is empty and doesn't appear to be used. Please remove it.

### Add more content to each article

In `server.js` you create articles that have a `title` and `content`. Per criteria 3, we would also like to see you add an image and a link.

### Remove `{ articles: articles }` from templates that don't use it

Your `index`, `about`, and `gallery` pages are being passed `articles`, but they don't ever use it. This code is taking up space and is misleading (I thought your articles might be linked from one of those pages).

In general, it's better to remove code that isn't being used to avoid confusion and reduce the chance of bugs being introduced later on.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🏓

**Comment by amanuel1995** [comment]
Made the requested changes.

**Comment by egillespie** [comment]
This is great! I like the UI changes that you made too. :shipit:

**Comment by amanuel1995** [comment]
Thanks Erik!
